project:
  output-dir: _book/2026-10-04
book:
  chapters:
  - chapters/00-introduction.qmd
  - chapters/01-argument-validity-proof.qmd
  appendices: []
metadata:
  sections:
    sec-introduction: true
    sec-introduction-why-study-logic: true
    sec-introduction-references: true
    sec-argument-validity-proof: true
    sec-argument-validity-proof-introduction: true
    sec-argument-validity-proof-arguments: true
    sec-argument-validity-proof-validity: true
    sec-argument-validity-proof-proofs: true
    sec-argument-validity-proof-soundness-and-completeness: true
    sec-argument-validity-proof-references-unnumbered: false
    sec-syllogistic-logic: false
    sec-syllogistic-logic-introduction: false
    sec-syllogistic-logic-the-syntax-and-semantics-of-syllogistic-logic: false
    sec-syllogistic-logic-proofs-in-syllogistic-logic: false
    sec-syllogistic-logic-the-extensional-soundness-and-completeness-of: false
    sec-syllogistic-logic-references-unnumbered: false
    sec-propositional-logic: false
    sec-propositional-logic-introduction: false
    sec-propositional-logic-the-syntax-and-semantics-of-propositional-logic: false
    sec-propositional-logic-proofs-in-propositional-logic: false
    sec-propositional-logic-the-soundness-and-completeness-of: false
    sec-propositional-logic-references-unnumbered: false
    sec-general-notation: false
    sec-general-notation-the-greek-alphabet: false
    sec-general-notation-iff: false
    sec-general-notation-ellipses: false
    sec-general-notation-sets: false
    sec-general-notation-references: false
    sec-induction: false
    sec-induction-inductive-definitions: false
    sec-induction-proof-by-induction: false
    sec-induction-unique-decomposition: false
