project:
  type: book
book:
  title: Accelerated Introduction to Logic
  comments:
    hypothesis: true
  page-navigation: true
  back-to-top-navigation: true
  chapters:
  - index.qmd
  sidebar:
    style: floating
    border: true
    collapse-level: 1
filters:
- lproof
format:
  html:
    theme: flatly
    css:
    - assets/styles/fonts.css
    - assets/styles/environments.css
    - assets/styles/tweaks.css
    - assets/styles/custom.css
    toc: true
    include-in-header:
    - assets/includes/scripts.html
