project:
  output-dir: _book/2026-10-20
book:
  chapters:
  - chapters/00-introduction.qmd
  - chapters/01-argument-validity-proof.qmd
  - chapters/02-syllogistic-logic.qmd
  - hw-01.qmd
  - hw-02.qmd
  - hw-03.qmd
  - hw-04.qmd
  appendices:
  - appendices/A-general-notation.qmd
  - appendices/B-induction.qmd
metadata:
  sections:
    sec-introduction: true
    sec-introduction-why-study-logic: true
    sec-introduction-references: true
    sec-argument-validity-proof: true
    sec-argument-validity-proof-introduction: true
    sec-argument-validity-proof-arguments: true
    sec-argument-validity-proof-validity: true
    sec-argument-validity-proof-proofs: true
    sec-argument-validity-proof-soundness-and-completeness: true
    sec-argument-validity-proof-references-unnumbered: true
    sec-syllogistic-logic: true
    sec-syllogistic-logic-introduction: true
    sec-syllogistic-logic-the-syntax-and-semantics-of-syllogistic-logic: true
    sec-syllogistic-logic-proofs-in-syllogistic-logic: false
    sec-syllogistic-logic-the-extensional-soundness-and-completeness-of: false
    sec-syllogistic-logic-references-unnumbered: true
    sec-propositional-logic: false
    sec-propositional-logic-introduction: false
    sec-propositional-logic-the-syntax-and-semantics-of-propositional-logic: false
    sec-propositional-logic-proofs-in-propositional-logic: false
    sec-propositional-logic-the-soundness-and-completeness-of: false
    sec-propositional-logic-references-unnumbered: false
    sec-general-notation: true
    sec-general-notation-the-greek-alphabet: true
    sec-general-notation-iff: true
    sec-general-notation-ellipses: true
    sec-general-notation-sets: true
    sec-general-notation-references: true
    sec-induction: true
    sec-induction-inductive-definitions: true
    sec-induction-proof-by-induction: true
    sec-induction-unique-decomposition: false
